web:
  build: .
  command: python /code/app/app.py
  ports:
   - "8082:8082"
  volumes:
   - .:/code
  links:
   - db
  hostname: myappserver
db:
  hostname: mysqlserver
  image: orchardup/mysql
  environment:
     MYSQL_ROOT_PASSWORD: p@ssw0rd123
     MYSQL_DATABASE: wordpress
